bitbot.neoSetPixelColor(5, bitbot.BBColours(BBColors.Violet))
bitbot.neoSetPixelColor(11, bitbot.BBColours(BBColors.Green))
bitbot.driveMilliseconds(600, 1000)
bitbot.driveTurnMilliseconds(BBRobotDirection.Right, 300, 650)
bitbot.driveMilliseconds(300, 900)
bitbot.driveTurnMilliseconds(BBRobotDirection.Right, 300, 650)
bitbot.driveMilliseconds(600, 1000)
bitbot.driveTurnMilliseconds(BBRobotDirection.Left, 300, 650)
bitbot.driveMilliseconds(300, 900)
bitbot.neoSetPixelColor(5, bitbot.BBColours(BBColors.Black))
bitbot.neoSetPixelColor(11, bitbot.BBColours(BBColors.Black))
basic.forever(function () {
    bitbot.neoSetPixelColor(6, bitbot.BBColours(BBColors.Black))
    bitbot.neoSetPixelColor(4, bitbot.BBColours(BBColors.White))
    bitbot.neoSetPixelColor(3, bitbot.BBColours(BBColors.Violet))
    bitbot.neoSetPixelColor(2, bitbot.BBColours(BBColors.Orange))
    bitbot.neoSetPixelColor(1, bitbot.BBColours(BBColors.Red))
    bitbot.neoSetPixelColor(0, bitbot.BBColours(BBColors.Yellow))
    bitbot.neoSetPixelColor(10, bitbot.BBColours(BBColors.Indigo))
    bitbot.neoSetPixelColor(9, bitbot.BBColours(BBColors.Violet))
    bitbot.neoSetPixelColor(8, bitbot.BBColours(BBColors.White))
    bitbot.neoSetPixelColor(7, bitbot.BBColours(BBColors.Orange))
    bitbot.driveMilliseconds(300, 400)
    bitbot.driveMilliseconds(-300, 400)
})
